<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" total="3" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="92546" started-at="2017-03-28T16:36:46Z" finished-at="2017-03-28T16:38:18Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="92546" started-at="2017-03-28T16:36:46Z" finished-at="2017-03-28T16:38:18Z">
      <class name="com.vh.ui.tests.LoginTest">
        <test-method status="PASS" signature="buildUp()[pri:0, instance:com.vh.ui.tests.LoginTest@2b0e9f30]" name="buildUp" is-config="true" duration-ms="5937" started-at="2017-03-28T11:36:46Z" finished-at="2017-03-28T11:36:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- buildUp -->
        <test-method status="PASS" signature="verify_InvalidPassword()[pri:0, instance:com.vh.ui.tests.LoginTest@2b0e9f30]" name="verify_InvalidPassword" duration-ms="28841" started-at="2017-03-28T11:36:52Z" finished-at="2017-03-28T11:37:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_InvalidPassword -->
        <test-method status="PASS" signature="afterTest(java.lang.reflect.Method, org.testng.ITestResult)[pri:0, instance:com.vh.ui.tests.LoginTest@2b0e9f30]" name="afterTest" is-config="true" duration-ms="7" started-at="2017-03-28T11:37:20Z" finished-at="2017-03-28T11:37:21Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.vh.ui.tests.LoginTest.verify_InvalidPassword() throws com.vh.ui.exceptions.WaitException,com.vh.ui.exceptions.URLNavigationException,java.lang.InterruptedException]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[TestResult name=verify_InvalidPassword status=SUCCESS method=LoginTest.verify_InvalidPassword()[pri:0, instance:com.vh.ui.tests.LoginTest@2b0e9f30] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="verify_InvalidUserName()[pri:0, instance:com.vh.ui.tests.LoginTest@2b0e9f30]" name="verify_InvalidUserName" duration-ms="20874" started-at="2017-03-28T11:37:21Z" finished-at="2017-03-28T11:37:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_InvalidUserName -->
        <test-method status="PASS" signature="afterTest(java.lang.reflect.Method, org.testng.ITestResult)[pri:0, instance:com.vh.ui.tests.LoginTest@2b0e9f30]" name="afterTest" is-config="true" duration-ms="0" started-at="2017-03-28T11:37:41Z" finished-at="2017-03-28T11:37:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.vh.ui.tests.LoginTest.verify_InvalidUserName() throws com.vh.ui.exceptions.WaitException,com.vh.ui.exceptions.URLNavigationException,java.lang.InterruptedException]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[TestResult name=verify_InvalidUserName status=SUCCESS method=LoginTest.verify_InvalidUserName()[pri:0, instance:com.vh.ui.tests.LoginTest@2b0e9f30] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="verify_SuccessfulLogin()[pri:0, instance:com.vh.ui.tests.LoginTest@2b0e9f30]" name="verify_SuccessfulLogin" duration-ms="36754" started-at="2017-03-28T11:37:41Z" finished-at="2017-03-28T11:38:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_SuccessfulLogin -->
        <test-method status="PASS" signature="afterTest(java.lang.reflect.Method, org.testng.ITestResult)[pri:0, instance:com.vh.ui.tests.LoginTest@2b0e9f30]" name="afterTest" is-config="true" duration-ms="0" started-at="2017-03-28T11:38:18Z" finished-at="2017-03-28T11:38:18Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.vh.ui.tests.LoginTest.verify_SuccessfulLogin() throws com.vh.ui.exceptions.WaitException,com.vh.ui.exceptions.URLNavigationException,java.lang.InterruptedException]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[TestResult name=verify_SuccessfulLogin status=SUCCESS method=LoginTest.verify_SuccessfulLogin()[pri:0, instance:com.vh.ui.tests.LoginTest@2b0e9f30] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="FAIL" signature="tearDown()[pri:0, instance:com.vh.ui.tests.LoginTest@2b0e9f30]" name="tearDown" is-config="true" duration-ms="0" started-at="2017-03-28T11:38:18Z" finished-at="2017-03-28T11:38:18Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.vh.ui.utilities.Utilities.highlightElement(Utilities.java:110)
	at com.vh.ui.actions.ApplicationFunctions.capellaLogOut(ApplicationFunctions.java:93)
	at com.vh.ui.tests.LoginTest.tearDown(LoginTest.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:232)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:115)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.vh.ui.tests.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
